# Site
title:              Spulhof
bio:                'Homepage des Spulhofs in Abtenau'
description:        "Unser Bauernhof befindet sich ca. 9 Kilometer ausserhalb des Ortszentrum. Abgeschieden mitten in der Natur, umgeben vom schönen Tennengebirge, sind Ihnen hier erholsame und ruhige Tage garantiert."
locale:             de_AT
baseurl: "/spulhof" # the subpath of your site, e.g. /blog
url: "spulhof.github.io/spulhof/" # the base hostname & protocol for your site
background_image:   /spulhof/images/bg_green.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
formspree_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
facebook:           default
instagram:          default

# personal
name:               Familie Wagenhofer
location:           Wagner 9 5441 Abtenau
phone:              0043 664 8901297
email:              spulhof@gmx.at

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-github-metadata

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
